from enum import IntEnum

WINDOWS_SUBSYSTEM = {
    0: 'IMAGE_SUBSYSTEM_UNKNOWN',
    1: 'IMAGE_SUBSYSTEM_NATIVE',
    2: 'IMAGE_SUBSYSTEM_WINDOWS_GUI',
    3: 'IMAGE_SUBSYSTEM_WINDOWS_CUI',
    5: 'IMAGE_SUBSYSTEM_OS2_CUI',
    7: 'IMAGE_SUBSYSTEM_POSIX_CUI',
    8: 'IMAGE_SUBSYSTEM_NATIVE_WINDOWS',
    9: 'IMAGE_SUBSYSTEM_WINDOWS_CE_GUI',
    10: 'IMAGE_SUBSYSTEM_EFI_APPLICATION',
    11: 'IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER',
    12: 'IMAGE_SUBSYSTEM_EFI_RUNTIME_RIVER',
    13: 'IMAGE_SUBSYSTEM_EFI_ROM',
    14: 'IMAGE_SUBSYSTEM_XBOX',
    16: 'IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION'
}
